apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
resources:
  - efs-provisioner.yml
  - efs-rbac.yml
  - efs-storage.yml
  - deploy-mysql.yaml
  - deploy-wordpress.yaml